name: fetch-from-simtropolis
description: Fetches a file from Simtropolis and generates metadata from it
inputs:
  url:
    description: File id or url. If not specified, fetches all files since the last run.
    optional: true
  require-metadata:
    description: Whether a metadata.yaml file is required to add the package. Useful to turn this off for testing.
    type: boolean
    default: true
  after:
    description: An ISO date string that holds the timestamp when the STEX api was last checked.
    type: string
    required: true
outputs:
  packages:
    description: Info about the packages that have been created, given as a stringified json array.
  timestamp:
    description: The timestamp when we last fetched from the STEX api. Can be empty if the timestamp shouldn't be logged.
  has-new-content:
    description: Holds whether new content is available for which PRs need to be created or updated. If "false", you can exit the action early. Nothing needs to be done.

runs:
  using: 'node20'
  main: 'action.js'
