group: agc
name: environment-dlc
version: "5.0.0"
subfolder: 180-flora
info:
  summary: Environment DLC
  description: |-
    This DLC will contain trees, plants, rocks, ponds and everything related to the environment.

    **Updated to version 5.0, see below to see what's new.**

    You can find images of what this DLC contains here:

    **Specs:**

    You can find them as MMP's and props **(Note that seasonal props end in "Summer" and "Autumn." I removed the winter state that means that the winter version is everwinter).**

    ![image.png.f22e9805a1e8ecc7176a3a7a7d306d73.png](https://www.simtropolis.com/objects/attachments/monthly_2021_12/image.png.f22e9805a1e8ecc7176a3a7a7d306d73.png)

    **I will update this DLC constantly so you must be on the lookout.**

    **Scale of the models:** **133% on all axes.**

    **Installation:**

    **Unzip the "Barroco Hispano DLCs" in your Plugins Folder (I highly recommend respecting my folder system because I plan to export or update thousands of BATs).**

    \-------------------------------------------------------------------------------------------------------

    **I will buy more trees with the money I receive (I decided to use Paypal instead of Patreon because I want everyone to have access to my content). ![*:thumb:](https://community.simtropolis.com/assets/emoticons/default_44.gif "*:thumb:")**

    [https://www.paypal.com/donate/?hosted\_button\_id=WF9FDNHXCHDVU](https://www.paypal.com/donate/?hosted_button_id=WF9FDNHXCHDVU)

    **Thanks to all people who have donated to me!**
  author: Barroco Hispano
  website: https://community.simtropolis.com/files/file/34720-agc-environment-dlc/
  images:
    - https://www.simtropolis.com/objects/screens/monthly_2021_10/ENVIRONMENT_ICON.png.9ef96068a94834cce519aed06c392fb8.png
dependencies:
  - agc:environment-dlc-props
assets:
  - assetId: agc-environment-dlc
    include:
      - .dat$

---
group: agc
name: environment-dlc-props
version: "5.0.0"
subfolder: 100-props-textures
info:
  summary: Environment DLC Props
  author: Barroco Hispano
  website: https://community.simtropolis.com/files/file/34720-agc-environment-dlc/
assets:
  - assetId: agc-environment-dlc
    include:
      - .SC4Desc$
      - .SC4Model$

---
assetId: agc-environment-dlc
version: "5.0.0"
lastModified: "2023-06-10T16:10:48Z"
url: https://community.simtropolis.com/files/file/34720-agc-environment-dlc/?do=download&r=197215
